Change the communication strategy to be chucked instead of blocked one
henrybarreto/walkietalkie pull request #6
Opened 2021-09-28 19:46 UTC by henrybarreto

2021-09-29 20:56 UTC, henrybarreto commented on src/radio.rs
> +        println!("DATA TO SEND: {:?}", data);
The data is sent here...

2021-09-29 21:09 UTC, henrybarreto commented on src/radio.rs
> +        println!("RECEIVED DATA: {:?}", data);
But when the other get the bytes, the total data differs only per 8 bytes in front of the original sent data.

2021-09-29 21:11 UTC, henrybarreto commented
I have no idea what is happening...

2021-09-29 22:51 UTC, otavio requested changes

2021-09-29 22:51 UTC, otavio commented on src/radio.rs
> +            }
```rust
tcp_stream.read(&mut buffer).map(|_| buffer)?
```

I believe this replace this ugly match.

2021-09-29 22:51 UTC, otavio commented on src/radio.rs
> +        let okay = Self::receive_bytes(1, tcp_connection_ref.try_clone()?)?;
`okay` is unused.

2021-09-29 23:39 UTC, merged

2021-10-01 00:30 UTC, nightlark commented
@henrybarreto not sure how you're using the `invalid` label, but you might want to avoid it except for PRs that are actually spam for the duration of hacktoberfest, since it seems like it could be counted towards bans.

2021-10-01 00:37 UTC, henrybarreto commented
> @henrybarreto not sure how you're using the `invalid` label, but you might want to avoid it except for PRs that are actually spam for the duration of hacktoberfest, since it seems like it could be counted towards bans.

Thanks! I will avoid this one when the event begins.